sudo: required
language: cpp

os: linux
dist: bionic
compiler: gcc

addons:
  apt:
    packages:

      # MPICH
      # - mpich
      # - libmpich-dev
      
      # OpenMPI
      - openmpi-bin
      - libopenmpi-dev

# Handle git submodules
git:
    submodules: true

# before_install:
#   - eval "${MATRIX_EVAL}"
#   - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libopenmpi-dev; fi

  # - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  # # see https://github.com/travis-ci/travis-ci/issues/10275
  # - if [ $TRAVIS_OS_NAME == osx ]; then brew install gcc || brew link --overwrite gcc; fi
  # - if [ $TRAVIS_OS_NAME == osx ]; then brew install make; fi

install:
  - mkdir external/pebbl/build
  - cd external/pebbl/build
  - cmake -Denable_mpi=ON -Denable_examples=OFF ..
  - make
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake ..
  - make

# script:
#   - cmake --version
#   - cmake -H. -Bbuild
#   - cmake --build build --target all
