sudo: required
language: cpp
matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc
    # - os: osx
    #   compiler: clang
    # - os: osx
    #   compiler: gcc

# Handle git submodules
git:
    submodules: true

# before_install:
#   - eval "${MATRIX_EVAL}"
#   - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libopenmpi-dev; fi

  # - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  # # see https://github.com/travis-ci/travis-ci/issues/10275
  # - if [ $TRAVIS_OS_NAME == osx ]; then brew install gcc || brew link --overwrite gcc; fi
  # - if [ $TRAVIS_OS_NAME == osx ]; then brew install make; fi

install:
  - mkdir /build
  - mkdir external/pebbl/build
  - cd external/pebbl/build
  - cmake -Denable_mpi=ON -Denable_examples=OFF ..; make
  - cd ../../../build; cmake ..; make

# script:
#   - cmake --version
#   - cmake -H. -Bbuild
#   - cmake --build build --target all
