sudo: required
language: cpp

os: linux

matrix:
    include:
        # - dist: trusty
        # - dist: xenial
        - dist: bionic   # Ubuntu 18.04
	- dist: focal    # Ubuntu 20.04

compiler: gcc

addons:
  apt:
    packages:
      # OpenMPI
      - openmpi-bin
      - libopenmpi-dev

# Handle git submodules
git:
    submodules: true

install:
  - mkdir external/pebbl/build
  - cd external/pebbl/build
  - cmake -Denable_mpi=ON -Denable_examples=OFF ..
  - make
  - mkdir ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake ..
  - make

script:
  - ./rma ../data/cleveland.dat
  - mpirun -np 2 ./rma ../data/cleveland.dat
