mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_0" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_1" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_2" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_3" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_4" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_5" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_6" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_7" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_8" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cleveland.data_9" --maxCPUMinutes=60 ../data/paper/cleveland.data > cleveland_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_0" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_1" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_2" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_3" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_4" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_5" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_6" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_7" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_8" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_indian.data_9" --maxCPUMinutes=60 ../data/paper/indian.data > indian_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_0" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_1" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_2" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_3" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_4" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_5" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_6" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_7" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_8" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_breast.data_9" --maxCPUMinutes=60 ../data/paper/breast.data > breast_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_0" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_1" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_2" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_3" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_4" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_5" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_6" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_7" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_8" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_car.data_9" --maxCPUMinutes=60 ../data/paper/car.data > car_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_0" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_1" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_2" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_3" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_4" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_5" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_6" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_7" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_8" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc_bin.data_9" --maxCPUMinutes=60 ../data/paper/cmc_bin.data > cmc_bin_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_0" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_1" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_2" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_3" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_4" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_5" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_6" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_7" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_8" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_climate.data_9" --maxCPUMinutes=60 ../data/paper/climate.data > climate_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_0" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_1" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_2" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_3" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_4" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_5" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_6" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_7" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_8" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_hungheart.data_9" --maxCPUMinutes=60 ../data/paper/hungheart.data > hungheart_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_0" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_1" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_2" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_3" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_4" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_5" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_6" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_7" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_8" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_cmc.data_9" --maxCPUMinutes=60 ../data/paper/cmc.data > cmc_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_0" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_1" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_2" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_3" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_4" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_5" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_6" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_7" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_8" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_diabetes.data_9" --maxCPUMinutes=60 ../data/paper/diabetes.data > diabetes_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_0" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_1" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_2" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_3" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_4" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_5" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_6" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_7" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_8" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam.data_9" --maxCPUMinutes=60 ../data/paper/spam.data > spam_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_0" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_1" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_2" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_3" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_4" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_5" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_6" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_7" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_8" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_spam75.data_9" --maxCPUMinutes=60 ../data/paper/spam75.data > spam75_np_16_wt_9.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_0" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_0.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_1" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_1.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_2" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_2.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_3" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_3.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_4" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_4.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_5" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_5.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_6" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_6.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_7" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_7.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_8" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_8.out
mpirun -np 16 ./rma --nonUniformWt="../Boosting/weights/wt_parkinson.data_9" --maxCPUMinutes=60 ../data/paper/parkinson.data > parkinson_np_16_wt_9.out
